### ISSUE TITLE
Error after installation and press F2

### ISSUE THREAD

**Issue by ericandrewlewis** [blobbered/fzf_snippets#1]
After I install the plugin and press F2, this error came up:

<img width="1280" alt="screen shot 2018-12-02 at 7 06 22 pm" src="https://user-images.githubusercontent.com/1087646/49346839-fce81c80-f665-11e8-97c4-e4fd8e98b8bd.png">

**Comment by ericandrewlewis** [comment]
It looks like I can fix this by moving the `snippets/` directory into the `plugin/` folder. Perhaps the `templates_dir` could include an up-one-directory `../` path part to leave it in place. I don't know much about where files should go in a Vim plugin directory structure though!

Thanks for the plugin!

**Comment by blobbered** [comment]
Thanks for submitting. Should be fixed!
